version: 1.0.{build}
# branches:
#   only:
#     - master

environment:
  matrix: 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: win32
      ARCH: win32-msvc17
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      MSVCVERSION: v143
      MSVCYEAR: "vs2022"
      MSVCABR: "17"
      VC_VER: 17.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      platform: x64
      ARCH: x64-msvc17
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 17 2022 Win64"
      MSVCVERSION: v143
      MSVCYEAR: "vs2022"
      MSVCABR: "17"
      VC_VER: 17.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   platform: win32
    #   ARCH: win32-msvc16
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 16 2019"
    #   MSVCVERSION: v142
    #   MSVCYEAR: "vs2019"
    #   MSVCABR: "16"
    #   VC_VER: 16.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   platform: x64
    #   ARCH: x64-msvc16
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 16 2019 Win64"
    #   MSVCVERSION: v142
    #   MSVCYEAR: "vs2019"
    #   MSVCABR: "16"
    #   VC_VER: 16.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #   platform: win32
    #   ARCH: win32-msvc15
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 15 2017"
    #   MSVCVERSION: v141
    #   MSVCYEAR: "vs2017"
    #   MSVCABR: "15"
    #   VC_VER: 15.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #   platform: x64
    #   ARCH: x64-msvc15
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    #   MSVCVERSION: v141
    #   MSVCYEAR: "vs2017"
    #   MSVCABR: "15"
    #   VC_VER: 15.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: win32
    #   ARCH: win32-msvc9
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 9 2008"
    #   MSVCVERSION: v90
    #   MSVCYEAR: "vs2008"
    #   MSVCABR: "9"
    #   VC_VER: 9.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x64
    #   ARCH: x64-msvc9
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 9 2008 Win64"
    #   MSVCVERSION: v90
    #   MSVCYEAR: "vs2008"
    #   MSVCABR: "9"
    #   VC_VER: 9.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: win32
    #   ARCH: win32-msvc10
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 10 2010"
    #   MSVCVERSION: v100
    #   MSVCYEAR: "vs2010"
    #   MSVCABR: "10"
    #   VC_VER: 10.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x64
    #   ARCH: x64-msvc10
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
    #   MSVCVERSION: v100
    #   MSVCYEAR: "vs2010"
    #   MSVCABR: "10"
    #   VC_VER: 10.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: win32
    #   ARCH: win32-msvc12
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 12 2013"
    #   MSVCVERSION: v120
    #   MSVCYEAR: "vs2013"
    #   MSVCABR: "13"
    #   VC_VER: 13.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x64
    #   ARCH: x64-msvc12
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
    #   MSVCVERSION: v120
    #   MSVCYEAR: "vs2013"
    #   MSVCABR: "13"
    #   VC_VER: 13.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: win32
    #   ARCH: win32-msvc14
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 14 2015"
    #   MSVCVERSION: v140
    #   MSVCYEAR: "vs2015"
    #   MSVCABR: "14"
    #   VC_VER: 14.0
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #   platform: x64
    #   ARCH: x64-msvc14
    #   configuration: Release
    #   CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    #   MSVCVERSION: v140
    #   MSVCYEAR: "vs2015"
    #   MSVCABR: "14"
    #   VC_VER: 14.0
init:
  # Set variable if perform old msvc patch and remove xamarin
  - cmd: set OLD_VERSION_PATCH=0
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%" NEQ "Visual Studio 2017" if "%APPVEYOR_BUILD_WORKER_IMAGE%" NEQ "Visual Studio 2019" if "%APPVEYOR_BUILD_WORKER_IMAGE%" NEQ "Visual Studio 2022" set OLD_VERSION_PATCH=1 

  # go to hell Xamarin (see http://help.appveyor.com/discussions/problems/4569)
  - cmd: if %OLD_VERSION_PATCH%==1 del "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.Targets\ImportAfter\Xamarin.Common.targets"
  - cmd: if %OLD_VERSION_PATCH%==1 del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - cmd: if %OLD_VERSION_PATCH%==1 del "C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  #RDP from start
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #Pthread-Win32
  - cmd: cd "C:\projects\"
  - cmd: md pthreads-win32-src
  - cmd: cd "C:\projects\"
  - appveyor DownloadFile "http://www.mirrorservice.org/sites/sources.redhat.com/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip"
  - cmd: 7z -y x pthreads-w32-2-9-1-release.zip -oC:\projects\pthreads-win32-src\
  #VS2008 patch
  - cmd: cd "C:\projects\"
  - cmd: if %OLD_VERSION_PATCH%==1 appveyor DownloadFile https://github.com/menpo/condaci/raw/master/vs2008_patch.zip
  - cmd: if %OLD_VERSION_PATCH%==1 7z -y x vs2008_patch.zip -oC:\projects\vs2008_patch\
  - cmd: if %ARCH%==x64-msvc9 call C:\projects\vs2008_patch\setup_x64.bat
  - cmd: if %ARCH%==x32-msvc9 call C:\projects\vs2008_patch\setup_x86.bat
  - cmd: if %OLD_VERSION_PATCH%==1 copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
  - cmd: cd "C:\projects\Pthread_WIN32"
  
install:
  - cmd: echo "Check Microsoft Visual Studio versions"
  - cmd: dir "C:\Program Files (x86)\Microsoft Visual Studio"
  - cmd: dir "C:\Program Files\Microsoft Visual Studio"
  - cmd: cd "C:\projects\Pthread_WIN32"
  - cmd: md bin
  - cmd: md lib
  - cmd: md include
  - cmd: dir
  - cmd: cd "C:\projects\"
  # Setting Visual Compiler
  - cmd: if %ARCH%==win32-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc9 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc10 call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc10 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc10 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 
  - cmd: if %ARCH%==win32-msvc12 call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==x64-msvc12 call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cmd: if %ARCH%==win32-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==x64-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: if %ARCH%==win32-msvc15 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: if %ARCH%==x64-msvc15 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc16 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: if %ARCH%==x64-msvc16 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc17 call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: if %ARCH%==x64-msvc17 call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  # - cmd: set PYTHONPATH=%PYTHONPATH%
  - cmd: set ARCH=%ARCH%

clone_folder: C:\projects\Pthread_WIN32

build:
  parallel: true
  verbosity: minimal
  
build_script:
  - cmd: set ARCH=%ARCH%
  - cmd: if %ARCH%==win32-msvc14 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile
  - cmd: if %ARCH%==x64-msvc14 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile
  - cmd: if %ARCH%==x64-msvc15 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile
  - cmd: if %ARCH%==win32-msvc15 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile
  - cmd: if %ARCH%==x64-msvc16 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile
  - cmd: if %ARCH%==win32-msvc16 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile
  - cmd: if %ARCH%==x64-msvc17 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile
  - cmd: if %ARCH%==win32-msvc17 move /Y C:\projects\Pthread_WIN32\Makefile C:\projects\pthreads-win32-src\pthreads.2\Makefile

  - cmd: type "C:\projects\pthreads-win32-src\pthreads.2\Makefile"
  - cmd: cd C:/projects/pthreads-win32-src/pthreads.2
  - cmd: nmake VC-static
  - cmd: dir
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2.lib C:\projects\Pthread_WIN32\lib\pthreadVC2-s.lib
  - cmd: nmake VC-static-debug
  - cmd: dir
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2d.lib C:\projects\Pthread_WIN32\lib\pthreadVC2-sd.lib
  - cmd: nmake VC
  - cmd: dir
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2.dll C:\projects\Pthread_WIN32\bin\pthreadVC2.dll
  #- cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2.dll.manifest C:\projects\Pthread_WIN32\bin\pthreadVC2.dll.manifest
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2.exp C:\projects\Pthread_WIN32\bin\pthreadVC2.exp
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2.ilk C:\projects\Pthread_WIN32\bin\pthreadVC2.ilk
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2.lib C:\projects\Pthread_WIN32\lib\pthreadVC2.lib
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2.pdb C:\projects\Pthread_WIN32\bin\pthreadVC2.pdb
  - cmd: nmake VC-debug
  - cmd: dir
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2d.dll C:\projects\Pthread_WIN32\bin\pthreadVC2d.dll
  #- cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2d.dll.manifest C:\projects\Pthread_WIN32\bin\pthreadVC2d.dll.manifest
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2d.exp C:\projects\Pthread_WIN32\bin\pthreadVC2d.exp
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2d.ilk C:\projects\Pthread_WIN32\bin\pthreadVC2d.ilk
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2d.lib C:\projects\Pthread_WIN32\lib\pthreadVC2d.lib
  - cmd: move C:\projects\pthreads-win32-src\pthreads.2\pthreadVC2d.pdb C:\projects\Pthread_WIN32\bin\pthreadVC2d.pdb
  - cmd: move C:\projects\pthreads-win32-src\Pre-built.2\include\*.* C:\projects\Pthread_WIN32\include


after_build:
  - cmd: cd "C:/projects/Pthread_WIN32"
  # Generating zip
  - cmd: 7z a pthreads-win32-2.9.1_%ARCH%.zip C:/projects/Pthread_WIN32\bin\
  - cmd: 7z a pthreads-win32-2.9.1_%ARCH%.zip C:/projects/Pthread_WIN32\lib\
  - cmd: 7z a pthreads-win32-2.9.1_%ARCH%.zip C:/projects/Pthread_WIN32\include\


on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: ./*.zip
